--
-- PostgreSQL database dump
--

\restrict CHX1ZOtMV38O6syct3CccDU3TQMW8dHmcgaavT2HI63fDCthG3ZEtmeBATfMQ6F

-- Dumped from database version 18.3 (Homebrew)
-- Dumped by pg_dump version 18.3 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addresses (
    id bigint NOT NULL,
    addressable_type character varying(255) NOT NULL,
    addressable_id bigint NOT NULL,
    nickname character varying(80) DEFAULT NULL::character varying,
    country character varying(255) NOT NULL,
    street_address character varying(255) NOT NULL,
    unit_number character varying(255) DEFAULT NULL::character varying,
    city character varying(255) DEFAULT NULL::character varying,
    state character varying(255) DEFAULT NULL::character varying,
    postal_code character varying(255) DEFAULT NULL::character varying,
    latitude double precision,
    longitude double precision,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animal_morph; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animal_morph (
    id bigint NOT NULL,
    animal_id bigint NOT NULL,
    morph_id bigint NOT NULL,
    homozygous boolean DEFAULT false NOT NULL,
    proven_het boolean DEFAULT false NOT NULL,
    percent_poss_het smallint DEFAULT 0 NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: animal_morph_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.animal_morph ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animal_morph_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.animals (
    id bigint NOT NULL,
    pet_name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    acquisition_cost integer,
    acquisition_date date,
    breeder_id bigint,
    vendor_id bigint,
    field_observation_id bigint,
    brood_id bigint,
    date_of_birth date,
    description text,
    notes jsonb,
    female boolean DEFAULT false NOT NULL,
    proven_breeder boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    user_id bigint,
    status character varying(255) DEFAULT 'draft'::character varying NOT NULL,
    mm_url character varying(255),
    category character varying(255),
    availability character varying(255),
    price numeric(10,2),
    species_id bigint,
    CONSTRAINT animals_status_check CHECK (((status)::text = ANY (ARRAY[('draft'::character varying)::text, ('published'::character varying)::text])))
);


--
-- Name: COLUMN animals.availability; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.animals.availability IS 'for_sale | breeder | sold | not_for_sale';


--
-- Name: animals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.animals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appellation_species; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appellation_species (
    id bigint NOT NULL,
    appellation_id bigint NOT NULL,
    species_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: appellation_species_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appellation_species ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appellation_species_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appellations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appellations (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: appellations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appellations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appellations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    subtitle character varying(255) DEFAULT NULL::character varying,
    body text NOT NULL,
    custom_data jsonb NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: breeders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.breeders (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    email character varying(140) DEFAULT NULL::character varying,
    website character varying(255) DEFAULT NULL::character varying,
    morph_market character varying(255) DEFAULT NULL::character varying,
    facebook character varying(255) DEFAULT NULL::character varying,
    instagram character varying(255) DEFAULT NULL::character varying,
    youtube character varying(255) DEFAULT NULL::character varying,
    phone character varying(255) DEFAULT NULL::character varying,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: breeders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.breeders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.breeders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: broods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.broods (
    id bigint NOT NULL,
    breeder_id bigint NOT NULL,
    laid_on date,
    first_pip date,
    born date,
    total_eggs smallint,
    eggs_viable smallint DEFAULT 0 NOT NULL,
    viable_progeny_total smallint DEFAULT 0 NOT NULL,
    viable_males smallint DEFAULT 0 NOT NULL,
    viable_females smallint DEFAULT 0 NOT NULL,
    viable_unsexed smallint DEFAULT 0 NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: broods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.broods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.broods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classifieds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classifieds (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    status character varying(255) DEFAULT 'published'::character varying NOT NULL,
    slug character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT classifieds_status_check CHECK (((status)::text = ANY (ARRAY[('draft'::character varying)::text, ('published'::character varying)::text, ('sold'::character varying)::text])))
);


--
-- Name: classifieds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.classifieds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: classifieds_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.classifieds_id_seq OWNED BY public.classifieds.id;


--
-- Name: complex_morph; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.complex_morph (
    id bigint NOT NULL,
    complex_id bigint NOT NULL,
    morph_id bigint NOT NULL,
    notes text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: complex_morph_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.complex_morph ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.complex_morph_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: complexes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.complexes (
    id bigint NOT NULL,
    species_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: complexes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.complexes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.complexes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: failed_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.failed_jobs (
    id bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    connection text NOT NULL,
    queue text NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: failed_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.failed_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.failed_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedings (
    id bigint NOT NULL,
    offered_at timestamp without time zone NOT NULL,
    food_items jsonb NOT NULL,
    refused boolean DEFAULT false NOT NULL,
    notes text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: feedings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feedings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: field_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.field_observations (
    id bigint NOT NULL,
    species_id bigint NOT NULL,
    title text NOT NULL,
    notes text NOT NULL,
    observed date NOT NULL,
    specific_time timestamp without time zone NOT NULL,
    latitude double precision,
    longitude double precision,
    collected boolean DEFAULT false NOT NULL,
    doa boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: field_observations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.field_observations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.field_observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inquiries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inquiries (
    id bigint NOT NULL,
    animal_id bigint,
    user_id bigint,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(255),
    message text NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    classified_id bigint,
    status character varying(255) DEFAULT 'new'::character varying NOT NULL
);


--
-- Name: inquiries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.inquiries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: inquiries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.inquiries_id_seq OWNED BY public.inquiries.id;


--
-- Name: inquiry_replies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inquiry_replies (
    id bigint NOT NULL,
    inquiry_id bigint NOT NULL,
    admin_user_id bigint,
    body text NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


--
-- Name: inquiry_replies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.inquiry_replies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: inquiry_replies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.inquiry_replies_id_seq OWNED BY public.inquiry_replies.id;


--
-- Name: invoiceable; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoiceable (
    invoice_id bigint NOT NULL,
    invoiceable_id bigint NOT NULL,
    invoiceable_type character varying(255) NOT NULL
);


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoices (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    deposit_requested bigint DEFAULT '0'::bigint NOT NULL,
    total integer DEFAULT 0 NOT NULL,
    paid integer DEFAULT 0 NOT NULL,
    remaining integer DEFAULT 0 NOT NULL,
    paid_in_full boolean DEFAULT false NOT NULL,
    due_date date DEFAULT '2026-04-21'::date NOT NULL,
    deleted_at timestamp(0) without time zone,
    created_at timestamp(0) with time zone,
    updated_at timestamp(0) with time zone
);


--
-- Name: invoices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: invoices_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.invoices_id_seq OWNED BY public.invoices.id;


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    queue character varying(255) NOT NULL,
    payload text NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL
);


--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- Name: measurements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.measurements (
    id bigint NOT NULL,
    animal_id bigint NOT NULL,
    grams bigint NOT NULL,
    height_cm integer,
    scale_rows_mid_body_cm integer,
    diameter_mid_body_cm integer,
    length_full_cm integer,
    length_svl_cm integer,
    taken_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    birth_measurement boolean DEFAULT false NOT NULL
);


--
-- Name: measurements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.measurements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measurements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media (
    id bigint NOT NULL,
    url character varying(255) NOT NULL,
    mediable_type character varying(255) NOT NULL,
    mediable_id bigint NOT NULL,
    license character varying(255) DEFAULT ''::character varying,
    exif jsonb,
    copyright text,
    author text,
    latitude numeric(10,8) DEFAULT NULL::numeric,
    longitude numeric(11,8) DEFAULT NULL::numeric,
    title text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    user_id bigint NOT NULL,
    moderation_status character varying(10) DEFAULT 'approved'::character varying NOT NULL,
    source_url text,
    license_url character varying(512)
);


--
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL
);


--
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: morphs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.morphs (
    id bigint NOT NULL,
    species_id bigint NOT NULL,
    complex_id bigint NOT NULL,
    name character varying(255) DEFAULT '0'::character varying NOT NULL,
    description text,
    recessive character varying(255) DEFAULT '0'::character varying NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: morphs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.morphs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.morphs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notes (
    id bigint NOT NULL,
    notable_type character varying(255) NOT NULL,
    notable_id bigint NOT NULL,
    content text NOT NULL,
    custom_data jsonb,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oauth_access_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_access_tokens (
    id character varying(100) NOT NULL,
    user_id bigint,
    client_id bigint NOT NULL,
    name character varying(255) DEFAULT NULL::character varying,
    scopes text,
    revoked boolean NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    expires_at timestamp without time zone
);


--
-- Name: oauth_auth_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_auth_codes (
    id character varying(100) NOT NULL,
    user_id bigint NOT NULL,
    client_id bigint NOT NULL,
    scopes text,
    revoked boolean NOT NULL,
    expires_at timestamp without time zone
);


--
-- Name: oauth_clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_clients (
    id bigint NOT NULL,
    user_id bigint,
    name character varying(255) NOT NULL,
    secret character varying(100) DEFAULT NULL::character varying,
    provider character varying(255) DEFAULT NULL::character varying,
    redirect text NOT NULL,
    personal_access_client boolean NOT NULL,
    password_client boolean NOT NULL,
    revoked boolean NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: oauth_clients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.oauth_clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth_clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oauth_personal_access_clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_personal_access_clients (
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: oauth_personal_access_clients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.oauth_personal_access_clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth_personal_access_clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oauth_refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_refresh_tokens (
    id character varying(100) NOT NULL,
    access_token_id character varying(100) NOT NULL,
    revoked boolean NOT NULL,
    expires_at timestamp without time zone
);


--
-- Name: pairings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pairings (
    id bigint NOT NULL,
    dam_id bigint NOT NULL,
    sire_id bigint NOT NULL,
    introduced_on_date date,
    observed boolean DEFAULT false NOT NULL,
    observed_on_date date,
    separated_on_date date,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: pairings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pairings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pairings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    email character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    created_at timestamp without time zone
);


--
-- Name: password_resets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_resets (
    email character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    created_at timestamp without time zone
);


--
-- Name: personal_access_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personal_access_tokens (
    id bigint NOT NULL,
    tokenable_type character varying(255) NOT NULL,
    tokenable_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    token character varying(64) NOT NULL,
    abilities text,
    last_used_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: personal_access_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personal_access_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personal_access_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pulse_aggregates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pulse_aggregates (
    id bigint NOT NULL,
    bucket integer NOT NULL,
    period integer NOT NULL,
    type character varying(255) NOT NULL,
    key text NOT NULL,
    key_hash uuid GENERATED ALWAYS AS ((md5(key))::uuid) STORED NOT NULL,
    aggregate character varying(255) NOT NULL,
    value numeric(20,2) NOT NULL,
    count integer
);


--
-- Name: pulse_aggregates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pulse_aggregates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pulse_aggregates_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pulse_aggregates_id_seq OWNED BY public.pulse_aggregates.id;


--
-- Name: pulse_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pulse_entries (
    id bigint NOT NULL,
    "timestamp" integer NOT NULL,
    type character varying(255) NOT NULL,
    key text NOT NULL,
    key_hash uuid GENERATED ALWAYS AS ((md5(key))::uuid) STORED NOT NULL,
    value bigint
);


--
-- Name: pulse_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pulse_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pulse_entries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pulse_entries_id_seq OWNED BY public.pulse_entries.id;


--
-- Name: pulse_values; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pulse_values (
    id bigint NOT NULL,
    "timestamp" integer NOT NULL,
    type character varying(255) NOT NULL,
    key text NOT NULL,
    key_hash uuid GENERATED ALWAYS AS ((md5(key))::uuid) STORED NOT NULL,
    value text NOT NULL
);


--
-- Name: pulse_values_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pulse_values_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pulse_values_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pulse_values_id_seq OWNED BY public.pulse_values.id;


--
-- Name: sellers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sellers (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) DEFAULT ''::character varying NOT NULL,
    email character varying(140) DEFAULT NULL::character varying,
    website character varying(255) DEFAULT NULL::character varying,
    instagram character varying(255) DEFAULT NULL::character varying,
    morph_market character varying(255) DEFAULT NULL::character varying,
    created_at timestamp without time zone,
    description text,
    phone character varying(255) DEFAULT NULL::character varying,
    youtube character varying(255) DEFAULT NULL::character varying,
    facebook character varying(255) DEFAULT NULL::character varying,
    updated_at timestamp without time zone,
    user_id bigint
);


--
-- Name: sellers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sellers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sellers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    id character varying(255) NOT NULL,
    user_id bigint,
    ip_address character varying(45) DEFAULT NULL::character varying,
    user_agent text,
    payload text NOT NULL,
    last_activity integer NOT NULL
);


--
-- Name: social_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.social_accounts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider character varying(32) NOT NULL,
    provider_id character varying(255) NOT NULL,
    name character varying(255),
    email character varying(255),
    nickname character varying(255),
    avatar text,
    token text NOT NULL,
    refresh_token text,
    token_expires_at timestamp(0) without time zone,
    provider_data json,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


--
-- Name: social_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.social_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: social_accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.social_accounts_id_seq OWNED BY public.social_accounts.id;


--
-- Name: species; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.species (
    id bigint NOT NULL,
    species character varying(255) DEFAULT ''::character varying NOT NULL,
    author character varying(255) DEFAULT NULL::character varying,
    subspecies text,
    common_name text,
    higher_taxa character varying(255) DEFAULT NULL::character varying,
    species_number character varying(255) DEFAULT NULL::character varying,
    changes character varying(255) DEFAULT NULL::character varying,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    type_species character varying(10)
);


--
-- Name: species_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.species ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.species_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subspecies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subspecies (
    id bigint NOT NULL,
    species_id bigint NOT NULL,
    genus character varying(255) NOT NULL,
    species character varying(255) NOT NULL,
    subspecies character varying(255) NOT NULL,
    author character varying(255),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    description text
);


--
-- Name: subspecies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.subspecies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: subspecies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.subspecies_id_seq OWNED BY public.subspecies.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    email_verified_at timestamp without time zone,
    password character varying(255) NOT NULL,
    two_factor_secret text,
    two_factor_recovery_codes text,
    remember_token character varying(100) DEFAULT NULL::character varying,
    profile_photo_path text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    is_admin boolean DEFAULT false NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vet_visits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vet_visits (
    id bigint NOT NULL,
    animal_id bigint NOT NULL,
    veterinarian_id bigint NOT NULL,
    cost integer NOT NULL,
    date_of_visit date NOT NULL,
    reason_for_visit character varying(255) NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: vet_visits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vet_visits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vet_visits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: veterinarians; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.veterinarians (
    id bigint NOT NULL,
    doctor_name character varying(255) NOT NULL,
    clinic_name character varying(255) DEFAULT NULL::character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: veterinarians_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.veterinarians ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.veterinarians_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classifieds id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classifieds ALTER COLUMN id SET DEFAULT nextval('public.classifieds_id_seq'::regclass);


--
-- Name: inquiries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries ALTER COLUMN id SET DEFAULT nextval('public.inquiries_id_seq'::regclass);


--
-- Name: inquiry_replies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry_replies ALTER COLUMN id SET DEFAULT nextval('public.inquiry_replies_id_seq'::regclass);


--
-- Name: invoices id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices ALTER COLUMN id SET DEFAULT nextval('public.invoices_id_seq'::regclass);


--
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- Name: pulse_aggregates id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pulse_aggregates ALTER COLUMN id SET DEFAULT nextval('public.pulse_aggregates_id_seq'::regclass);


--
-- Name: pulse_entries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pulse_entries ALTER COLUMN id SET DEFAULT nextval('public.pulse_entries_id_seq'::regclass);


--
-- Name: pulse_values id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pulse_values ALTER COLUMN id SET DEFAULT nextval('public.pulse_values_id_seq'::regclass);


--
-- Name: social_accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts ALTER COLUMN id SET DEFAULT nextval('public.social_accounts_id_seq'::regclass);


--
-- Name: subspecies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subspecies ALTER COLUMN id SET DEFAULT nextval('public.subspecies_id_seq'::regclass);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: animal_morph animal_morph_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_morph
    ADD CONSTRAINT animal_morph_pkey PRIMARY KEY (id);


--
-- Name: animals animals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_pkey PRIMARY KEY (id);


--
-- Name: animals animals_slug_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_slug_unique UNIQUE (slug);


--
-- Name: appellation_species appellation_species_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appellation_species
    ADD CONSTRAINT appellation_species_pkey PRIMARY KEY (id);


--
-- Name: appellations appellations_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appellations
    ADD CONSTRAINT appellations_name_unique UNIQUE (name);


--
-- Name: appellations appellations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appellations
    ADD CONSTRAINT appellations_pkey PRIMARY KEY (id);


--
-- Name: appellations appellations_slug_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appellations
    ADD CONSTRAINT appellations_slug_unique UNIQUE (slug);


--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: articles articles_slug_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_slug_unique UNIQUE (slug);


--
-- Name: articles articles_title_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_title_unique UNIQUE (title);


--
-- Name: breeders breeders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.breeders
    ADD CONSTRAINT breeders_pkey PRIMARY KEY (id);


--
-- Name: breeders breeders_slug_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.breeders
    ADD CONSTRAINT breeders_slug_unique UNIQUE (slug);


--
-- Name: broods broods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.broods
    ADD CONSTRAINT broods_pkey PRIMARY KEY (id);


--
-- Name: classifieds classifieds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classifieds
    ADD CONSTRAINT classifieds_pkey PRIMARY KEY (id);


--
-- Name: classifieds classifieds_slug_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classifieds
    ADD CONSTRAINT classifieds_slug_unique UNIQUE (slug);


--
-- Name: complex_morph complex_morph_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complex_morph
    ADD CONSTRAINT complex_morph_pkey PRIMARY KEY (id);


--
-- Name: complexes complexes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complexes
    ADD CONSTRAINT complexes_pkey PRIMARY KEY (id);


--
-- Name: failed_jobs failed_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.failed_jobs
    ADD CONSTRAINT failed_jobs_pkey PRIMARY KEY (id);


--
-- Name: feedings feedings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedings
    ADD CONSTRAINT feedings_pkey PRIMARY KEY (id);


--
-- Name: field_observations field_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.field_observations
    ADD CONSTRAINT field_observations_pkey PRIMARY KEY (id);


--
-- Name: inquiries inquiries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_pkey PRIMARY KEY (id);


--
-- Name: inquiry_replies inquiry_replies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry_replies
    ADD CONSTRAINT inquiry_replies_pkey PRIMARY KEY (id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: measurements measurements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT measurements_pkey PRIMARY KEY (id);


--
-- Name: media media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


--
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- Name: morphs morphs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.morphs
    ADD CONSTRAINT morphs_pkey PRIMARY KEY (id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: oauth_access_tokens oauth_access_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_access_tokens
    ADD CONSTRAINT oauth_access_tokens_pkey PRIMARY KEY (id);


--
-- Name: oauth_auth_codes oauth_auth_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_auth_codes
    ADD CONSTRAINT oauth_auth_codes_pkey PRIMARY KEY (id);


--
-- Name: oauth_clients oauth_clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_clients
    ADD CONSTRAINT oauth_clients_pkey PRIMARY KEY (id);


--
-- Name: oauth_personal_access_clients oauth_personal_access_clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_personal_access_clients
    ADD CONSTRAINT oauth_personal_access_clients_pkey PRIMARY KEY (id);


--
-- Name: oauth_refresh_tokens oauth_refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: pairings pairings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pairings
    ADD CONSTRAINT pairings_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email);


--
-- Name: personal_access_tokens personal_access_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_pkey PRIMARY KEY (id);


--
-- Name: personal_access_tokens personal_access_tokens_token_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_token_unique UNIQUE (token);


--
-- Name: pulse_aggregates pulse_aggregates_bucket_period_type_aggregate_key_hash_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pulse_aggregates
    ADD CONSTRAINT pulse_aggregates_bucket_period_type_aggregate_key_hash_unique UNIQUE (bucket, period, type, aggregate, key_hash);


--
-- Name: pulse_aggregates pulse_aggregates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pulse_aggregates
    ADD CONSTRAINT pulse_aggregates_pkey PRIMARY KEY (id);


--
-- Name: pulse_entries pulse_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pulse_entries
    ADD CONSTRAINT pulse_entries_pkey PRIMARY KEY (id);


--
-- Name: pulse_values pulse_values_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pulse_values
    ADD CONSTRAINT pulse_values_pkey PRIMARY KEY (id);


--
-- Name: pulse_values pulse_values_type_key_hash_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pulse_values
    ADD CONSTRAINT pulse_values_type_key_hash_unique UNIQUE (type, key_hash);


--
-- Name: sellers sellers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT sellers_pkey PRIMARY KEY (id);


--
-- Name: sellers sellers_user_id_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT sellers_user_id_unique UNIQUE (user_id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: social_accounts social_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_pkey PRIMARY KEY (id);


--
-- Name: social_accounts social_accounts_provider_provider_id_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_provider_provider_id_unique UNIQUE (provider, provider_id);


--
-- Name: species species_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.species
    ADD CONSTRAINT species_pkey PRIMARY KEY (id);


--
-- Name: species species_species_number_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.species
    ADD CONSTRAINT species_species_number_unique UNIQUE (species_number);


--
-- Name: subspecies subspecies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subspecies
    ADD CONSTRAINT subspecies_pkey PRIMARY KEY (id);


--
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: sellers vendors_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT vendors_name_unique UNIQUE (name);


--
-- Name: sellers vendors_slug_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT vendors_slug_unique UNIQUE (slug);


--
-- Name: vet_visits vet_visits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vet_visits
    ADD CONSTRAINT vet_visits_pkey PRIMARY KEY (id);


--
-- Name: veterinarians veterinarians_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veterinarians
    ADD CONSTRAINT veterinarians_pkey PRIMARY KEY (id);


--
-- Name: 1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "1" ON public.morphs USING btree (species_id);


--
-- Name: addresses_addressable_type_addressable_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX addresses_addressable_type_addressable_id_index ON public.addresses USING btree (addressable_type, addressable_id);


--
-- Name: animal_morph_animal_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX animal_morph_animal_id_foreign ON public.animal_morph USING btree (animal_id);


--
-- Name: animal_morph_morph_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX animal_morph_morph_id_foreign ON public.animal_morph USING btree (morph_id);


--
-- Name: animals_availability_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX animals_availability_index ON public.animals USING btree (availability);


--
-- Name: animals_breeder_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX animals_breeder_id_foreign ON public.animals USING btree (breeder_id);


--
-- Name: animals_brood_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX animals_brood_id_foreign ON public.animals USING btree (brood_id);


--
-- Name: animals_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX animals_status_index ON public.animals USING btree (status);


--
-- Name: animals_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX animals_user_id_index ON public.animals USING btree (user_id);


--
-- Name: appellation_species_appellation_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX appellation_species_appellation_id_foreign ON public.appellation_species USING btree (appellation_id);


--
-- Name: appellation_species_species_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX appellation_species_species_id_foreign ON public.appellation_species USING btree (species_id);


--
-- Name: articles_user_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX articles_user_id_foreign ON public.articles USING btree (user_id);


--
-- Name: broods_breeder_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX broods_breeder_id_foreign ON public.broods USING btree (breeder_id);


--
-- Name: classifieds_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX classifieds_status_index ON public.classifieds USING btree (status);


--
-- Name: classifieds_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX classifieds_user_id_index ON public.classifieds USING btree (user_id);


--
-- Name: complex_morph_complex_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX complex_morph_complex_id_foreign ON public.complex_morph USING btree (complex_id);


--
-- Name: complex_morph_morph_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX complex_morph_morph_id_foreign ON public.complex_morph USING btree (morph_id);


--
-- Name: complexes_species_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX complexes_species_id_foreign ON public.complexes USING btree (species_id);


--
-- Name: field_observation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX field_observation_id ON public.animals USING btree (field_observation_id);


--
-- Name: field_observations_species_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX field_observations_species_id_index ON public.field_observations USING btree (species_id);


--
-- Name: inquiries_animal_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inquiries_animal_id_index ON public.inquiries USING btree (animal_id);


--
-- Name: inquiries_classified_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inquiries_classified_id_index ON public.inquiries USING btree (classified_id);


--
-- Name: inquiries_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inquiries_status_index ON public.inquiries USING btree (status);


--
-- Name: inquiry_replies_inquiry_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inquiry_replies_inquiry_id_index ON public.inquiry_replies USING btree (inquiry_id);


--
-- Name: jobs_queue_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX jobs_queue_index ON public.jobs USING btree (queue);


--
-- Name: media_mediable_type_mediable_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX media_mediable_type_mediable_id_index ON public.media USING btree (mediable_type, mediable_id);


--
-- Name: morphs_complex_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX morphs_complex_id_foreign ON public.morphs USING btree (complex_id);


--
-- Name: notes_notable_type_notable_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notes_notable_type_notable_id_index ON public.notes USING btree (notable_type, notable_id);


--
-- Name: oauth_access_tokens_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX oauth_access_tokens_user_id_index ON public.oauth_access_tokens USING btree (user_id);


--
-- Name: oauth_auth_codes_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX oauth_auth_codes_user_id_index ON public.oauth_auth_codes USING btree (user_id);


--
-- Name: oauth_clients_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX oauth_clients_user_id_index ON public.oauth_clients USING btree (user_id);


--
-- Name: oauth_refresh_tokens_access_token_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX oauth_refresh_tokens_access_token_id_index ON public.oauth_refresh_tokens USING btree (access_token_id);


--
-- Name: pairings_dam_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pairings_dam_id_foreign ON public.pairings USING btree (dam_id);


--
-- Name: pairings_sire_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pairings_sire_id_foreign ON public.pairings USING btree (sire_id);


--
-- Name: password_resets_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX password_resets_email_index ON public.password_resets USING btree (email);


--
-- Name: personal_access_tokens_tokenable_type_tokenable_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personal_access_tokens_tokenable_type_tokenable_id_index ON public.personal_access_tokens USING btree (tokenable_type, tokenable_id);


--
-- Name: pulse_aggregates_period_bucket_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_aggregates_period_bucket_index ON public.pulse_aggregates USING btree (period, bucket);


--
-- Name: pulse_aggregates_period_type_aggregate_bucket_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_aggregates_period_type_aggregate_bucket_index ON public.pulse_aggregates USING btree (period, type, aggregate, bucket);


--
-- Name: pulse_aggregates_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_aggregates_type_index ON public.pulse_aggregates USING btree (type);


--
-- Name: pulse_entries_key_hash_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_entries_key_hash_index ON public.pulse_entries USING btree (key_hash);


--
-- Name: pulse_entries_timestamp_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_entries_timestamp_index ON public.pulse_entries USING btree ("timestamp");


--
-- Name: pulse_entries_timestamp_type_key_hash_value_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_entries_timestamp_type_key_hash_value_index ON public.pulse_entries USING btree ("timestamp", type, key_hash, value);


--
-- Name: pulse_entries_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_entries_type_index ON public.pulse_entries USING btree (type);


--
-- Name: pulse_values_timestamp_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_values_timestamp_index ON public.pulse_values USING btree ("timestamp");


--
-- Name: pulse_values_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pulse_values_type_index ON public.pulse_values USING btree (type);


--
-- Name: sessions_last_activity_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sessions_last_activity_index ON public.sessions USING btree (last_activity);


--
-- Name: sessions_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sessions_user_id_index ON public.sessions USING btree (user_id);


--
-- Name: social_accounts_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX social_accounts_user_id_index ON public.social_accounts USING btree (user_id);


--
-- Name: subspecies_genus_species_subspecies_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX subspecies_genus_species_subspecies_index ON public.subspecies USING btree (genus, species, subspecies);


--
-- Name: subspecies_species_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX subspecies_species_id_index ON public.subspecies USING btree (species_id);


--
-- Name: vendor_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vendor_id ON public.animals USING btree (vendor_id);


--
-- Name: vet_visits_animal_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vet_visits_animal_id_index ON public.vet_visits USING btree (animal_id);


--
-- Name: vet_visits_veterinarian_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vet_visits_veterinarian_id_index ON public.vet_visits USING btree (veterinarian_id);


--
-- Name: weights_animal_id_foreign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX weights_animal_id_foreign ON public.measurements USING btree (animal_id);


--
-- Name: morphs 1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.morphs
    ADD CONSTRAINT "1" FOREIGN KEY (species_id) REFERENCES public.species(id);


--
-- Name: animal_morph animal_morph_animal_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_morph
    ADD CONSTRAINT animal_morph_animal_id_foreign FOREIGN KEY (animal_id) REFERENCES public.animals(id);


--
-- Name: animal_morph animal_morph_morph_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animal_morph
    ADD CONSTRAINT animal_morph_morph_id_foreign FOREIGN KEY (morph_id) REFERENCES public.morphs(id);


--
-- Name: animals animals_breeder_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_breeder_id_foreign FOREIGN KEY (breeder_id) REFERENCES public.breeders(id);


--
-- Name: animals animals_brood_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_brood_id_foreign FOREIGN KEY (brood_id) REFERENCES public.broods(id);


--
-- Name: animals animals_species_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_species_id_foreign FOREIGN KEY (species_id) REFERENCES public.species(id) ON DELETE SET NULL;


--
-- Name: animals animals_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: appellation_species appellation_species_appellation_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appellation_species
    ADD CONSTRAINT appellation_species_appellation_id_foreign FOREIGN KEY (appellation_id) REFERENCES public.appellations(id);


--
-- Name: appellation_species appellation_species_species_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appellation_species
    ADD CONSTRAINT appellation_species_species_id_foreign FOREIGN KEY (species_id) REFERENCES public.species(id);


--
-- Name: articles articles_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: broods broods_breeder_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.broods
    ADD CONSTRAINT broods_breeder_id_foreign FOREIGN KEY (breeder_id) REFERENCES public.breeders(id);


--
-- Name: classifieds classifieds_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classifieds
    ADD CONSTRAINT classifieds_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: complex_morph complex_morph_complex_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complex_morph
    ADD CONSTRAINT complex_morph_complex_id_foreign FOREIGN KEY (complex_id) REFERENCES public.complexes(id);


--
-- Name: complex_morph complex_morph_morph_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complex_morph
    ADD CONSTRAINT complex_morph_morph_id_foreign FOREIGN KEY (morph_id) REFERENCES public.morphs(id);


--
-- Name: complexes complexes_species_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.complexes
    ADD CONSTRAINT complexes_species_id_foreign FOREIGN KEY (species_id) REFERENCES public.species(id);


--
-- Name: inquiries inquiries_animal_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_animal_id_foreign FOREIGN KEY (animal_id) REFERENCES public.animals(id) ON DELETE CASCADE;


--
-- Name: inquiries inquiries_classified_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_classified_id_foreign FOREIGN KEY (classified_id) REFERENCES public.classifieds(id);


--
-- Name: inquiries inquiries_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: inquiry_replies inquiry_replies_admin_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry_replies
    ADD CONSTRAINT inquiry_replies_admin_user_id_foreign FOREIGN KEY (admin_user_id) REFERENCES public.users(id);


--
-- Name: inquiry_replies inquiry_replies_inquiry_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry_replies
    ADD CONSTRAINT inquiry_replies_inquiry_id_foreign FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id) ON DELETE CASCADE;


--
-- Name: invoiceable invoiceable_invoice_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoiceable
    ADD CONSTRAINT invoiceable_invoice_id_foreign FOREIGN KEY (invoice_id) REFERENCES public.invoices(id);


--
-- Name: invoices invoices_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: media media_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: morphs morphs_complex_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.morphs
    ADD CONSTRAINT morphs_complex_id_foreign FOREIGN KEY (complex_id) REFERENCES public.complexes(id);


--
-- Name: pairings pairings_dam_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pairings
    ADD CONSTRAINT pairings_dam_id_foreign FOREIGN KEY (dam_id) REFERENCES public.animals(id);


--
-- Name: pairings pairings_sire_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pairings
    ADD CONSTRAINT pairings_sire_id_foreign FOREIGN KEY (sire_id) REFERENCES public.animals(id);


--
-- Name: sellers sellers_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT sellers_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: social_accounts social_accounts_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: subspecies subspecies_species_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subspecies
    ADD CONSTRAINT subspecies_species_id_foreign FOREIGN KEY (species_id) REFERENCES public.species(id) ON DELETE SET NULL;


--
-- Name: measurements weights_animal_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT weights_animal_id_foreign FOREIGN KEY (animal_id) REFERENCES public.animals(id);


--
-- PostgreSQL database dump complete
--

\unrestrict CHX1ZOtMV38O6syct3CccDU3TQMW8dHmcgaavT2HI63fDCthG3ZEtmeBATfMQ6F

--
-- PostgreSQL database dump
--

\restrict gR2G9z6f04Y3xCOcpBW8ghSx4DlhDr0ANz3768o3llRtkDnwNaSD9aEQZJU3c4d

-- Dumped from database version 18.3 (Homebrew)
-- Dumped by pg_dump version 18.3 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.migrations (id, migration, batch) FROM stdin;
1	2014_10_12_000000_create_users_table	1
2	2014_10_12_100000_create_password_resets_table	1
3	2014_10_12_200000_add_two_factor_columns_to_users_table	1
4	2019_08_19_000000_create_failed_jobs_table	1
5	2019_12_14_000001_create_personal_access_tokens_table	1
6	2020_05_21_100000_create_teams_table	1
7	2020_05_21_200000_create_team_user_table	1
8	2020_05_21_300000_create_team_invitations_table	1
9	2021_04_20_183807_create_sessions_table	1
10	2021_04_30_000930_create_breeders_table	1
11	2021_04_30_000931_create_broods_table	1
12	2021_04_30_000932_create_genera_table	1
13	2021_04_30_000932_create_species_table	1
14	2021_04_30_000933_create_complexes_table	1
15	2021_04_30_000939_create_animals_table	1
16	2021_04_30_000940_create_pairings_table	1
17	2021_04_30_001844_create_morphs_table	1
18	2021_04_30_004123_create_images_table	1
19	2021_04_30_010742_create_animal_morph_table	1
20	2021_04_30_014413_create_addresses_table	1
21	2021_04_30_033846_create_complex_morph_table	1
22	2021_04_30_134459_create_feedings_table	1
23	2021_04_30_144135_create_weights_table	2
24	2021_04_30_150553_create_appellations_table	2
25	2021_04_30_151125_create_lengths_table	2
26	2021_04_30_152407_modify_animals_table	3
27	2021_04_30_182436_create_articles_table	4
28	2021_04_30_201941_modify_appellations_table	5
29	2021_04_30_202550_create_appellation_species_table	5
30	2021_04_30_221604_create_shipment_table	6
31	2021_05_01_030510_create_vendors_table	7
32	2021_05_01_031233_modify_animals_table	7
35	2021_05_21_015200_create_field_observations_table	8
36	2021_05_21_015213_modify_animals_table	9
38	2021_05_21_181701_modify_field_observations_table	10
39	2021_05_21_182710_modify_animals	10
40	2021_05_21_232510_create_notes_table	11
41	2021_06_07_160438_create_vet_visits_table	12
42	2014_10_12_100000_create_password_reset_tokens_table	13
43	2023_09_16_151038_rename_vendor_table_to_seller	13
44	2023_09_17_114828_rename_image_table_to_media	13
45	2023_09_17_114952_delete_genera_table	13
46	2023_09_17_115024_rename_weights_table_to_measurements	13
47	2023_09_17_115647_drop_lengths_table	13
48	2023_09_17_121006_add_fields_to_measurements_table	13
49	2016_06_01_000001_create_oauth_auth_codes_table	14
50	2016_06_01_000002_create_oauth_access_tokens_table	14
51	2016_06_01_000003_create_oauth_refresh_tokens_table	14
52	2016_06_01_000004_create_oauth_clients_table	14
53	2016_06_01_000005_create_oauth_personal_access_clients_table	14
54	2023_09_17_181126_drop_complexes_table	14
55	2023_09_17_181127_drop_complex_morph_table	14
56	2023_09_17_181835_rename_images_table	15
57	2023_09_17_181847_rename_vendors_table	15
58	2023_09_17_183343_create_invoices_table	16
59	2023_09_17_184639_create_invoiceable_table	16
60	2023_09_21_143516_add_user_id_to_media_table	16
61	2026_04_21_161459_create_classifieds_table	16
62	2026_04_21_200000_add_user_status_to_animals_table	17
63	2026_04_22_011646_add_is_admin_to_users_table	18
64	2026_04_22_015106_drop_animal_id_from_classifieds_table	18
65	2026_04_22_024801_add_mm_url_to_animals_table	18
66	2026_04_22_025119_add_category_to_animals_table	18
67	2026_04_22_161727_add_user_id_to_sellers_table	18
68	2026_04_22_171224_add_availability_to_animals_table	18
69	2026_04_22_200028_add_price_to_animals_table	18
70	2026_04_22_200028_create_inquiries_table	18
71	2026_04_22_201037_add_classified_id_to_inquiries_table	18
72	2026_04_27_000001_add_status_to_inquiries_table	18
73	2026_04_27_000002_create_inquiry_replies_table	18
74	2026_04_30_000001_create_social_accounts_table	19
75	2026_05_04_000001_update_species_table	20
76	2026_05_04_000002_add_moderation_status_to_media_table	21
77	2026_05_04_000003_add_species_id_to_animals_table	22
78	2026_05_04_000004_create_subspecies_table	23
79	2026_05_04_000005_add_attribution_fields_to_media_table	24
80	2026_05_04_000006_widen_media_text_columns	25
81	2026_05_05_014413_create_failed_jobs_table	26
82	2026_05_05_014413_create_jobs_table	26
83	2026_05_05_163336_add_description_to_subspecies_table	27
84	2023_06_07_000001_create_pulse_tables	28
\.


--
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.migrations_id_seq', 84, true);


--
-- PostgreSQL database dump complete
--

\unrestrict gR2G9z6f04Y3xCOcpBW8ghSx4DlhDr0ANz3768o3llRtkDnwNaSD9aEQZJU3c4d

